[package]
name = "itest"
version = "0.1.0"
edition = "2024"
authors = ["Jack Huang <jhaungyc@proton.me"]
keywords = ["test"]

[[bin]]
name = "test_bin"

[dependencies]
project-root = "0.2.2"
color-eyre = "0.6.5"
stdext = "0.3.3"
assert_cmd = "2.0"
